title: The Feast Mall of Asia
email: info@thefeastmallofasia
description: > # this means to ignore newlines until "baseurl:"
  A Catholic prayer meeting of the Light of Jesus family.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thefeastmallofasia.com" # the base hostname & protocol for your site, e.g. http://example.com

facebook: "https://www.facebook.com/TheFeastMallofAsia/"
intagram: "https://www.instagram.com/thefeastmallofasia/"



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
